language: python
python: "2.7"
install:
  - pip install pep8 pyflakes nose unittest2
  #- "pip install -r requirements.txt"
script:
  - nosetests -s -v
  - pyflakes normalize
  - pep8 normalize
  - pep8 --max-line-length=100 tests
